### ISSUE TITLE
Layout Support

### ISSUE THREAD

**Issue by chriswburke** [keithamus/hbs-cli#1]
How would you go about supporting a layout?

**Comment by keithamus** [comment]
Hey @chriswburke thanks for the issue. Have a look at [`@economist/doc-pack`](https://github.com/economist-components/doc-pack) which uses [`handlebars-layouts`](https://github.com/shannonmoeller/handlebars-layouts) as a helper, and then the layouts are just registered as partials. 

Hope this helps, let me know if not and I'll re-open 😄
