### ISSUE TITLE
Allow output to stdout

### ISSUE THREAD

**Issue by codingtony** [keithamus/hbs-cli#2]
I have found your project after using handlebars-cmd for a while.

I needed an updated version of handlebars since handlebars-cmd depends on an old version of handlebars.

It does everything ok but it would be very nice being able to output to stdout this way I could use the tool this way :

```
hbs --stdout --data data.json /templates/install.hbs  > install.sh
```

**Comment by keithamus** [comment]
Great idea! Fancy making a PR?

**Comment by keithamus** [comment]
@codingtony https://github.com/keithamus/hbs-cli/releases/tag/v1.1.0 😄 🎉

**Comment by codingtony** [comment]
@keithamus thanks!
